RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index")
]

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/menu/urls.py
from django.urls import path
from . import views

app_name = "menu"

urlpatterns = [
    path('', views.index, name="index")
]

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
]

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/main/models.py
from django.db import models

# Create your models here.

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/menu/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):
        return self.name

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/main/views.py
from django.shortcuts import render
# from django.http import HttpResponse


def index(request):
    return render(request, 'main/index.html')

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza

# Create your views here.

# EXERCISE
# Our pizzas : Vegetarian : 8.55$, 4 cheeses : xx, Chicken mushrooms : xxx, Meat lover

def index(request):
    '''pizzas = Pizza.objects.all()
    pizzas_names_and_price = [pizza.name + " : " + str(pizza.price) + "$" for pizza in pizzas]
    pizzas_names_and_price_str = ", ".join(pizzas_names_and_price)
    return HttpResponse("Our pizzas : " + pizzas_names_and_price_str)'''
    pizzas = Pizza.objects.all().order_by('price')
    return render(request, 'menu/index.html', {'pizzas': pizzas})

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img id="small_logo" src="{% static 'main/images/main_logo.png' %}"/>
        <a href="{% url 'menu:index' %}">See our menu</a>
    </div>
</body>
</html>

RESOURCES_PACK/2_WEB_DEVELOPMENT/5_PIZZA_MAMA_DJANGO/PizzaMamaDjango/pizzamama/menu/templates/menu/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Our pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}"/></a>


    <div class="menu_title">
        <h1>Our Pizzas</h1>
    </div>

    <div class="menu_list">
        {% for pizza in pizzas %}
            <div class="menu_list_item">
                <span class="menu_list_title">{{pizza.name}}</span>
                <span class="menu_list_price">{{pizza.price | floatformat:2}}$</span>
                <span class="menu_list_ingredients">{{pizza.ingredients}}</span>
                {% if pizza.vegetarian %}
                <span class="menu_list_badge">VEGETARIAN</span>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</body>
</html>